version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravelapp
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:5.7
#     container_name: laravelmysql
#     ports:
#       - "3307:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: laravelapp
#       MYSQL_USER: laraveluser
#       MYSQL_PASSWORD: laravelapp@123
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
