name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up known hosts
        run: ssh-keyscan -H 13.234.213.30 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ubuntu@ec2-13-234-213-30.ap-south-1.compute.amazonaws.com -i "D:\01DEVOPS\DevOps Practice\AWSKEY\Key\AWSKEY.pem" 'bash -s' < deploy.sh
